version: '3.8'

services:
  # 后端API服务（测试版）
  backend:
    build:
      context: .
      dockerfile: Dockerfile-test
    ports:
      - "1110:1110"
    environment:
      - NODE_ENV=production
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge 