version: '3.8'

services:
  # 后端API服务
  backend:
    build:
      context: .
    ports:
      - "1110:3001"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
    depends_on:
      - mysql
    networks:
      - backend-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ordercheck_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge 