version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "1100:1100"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 