version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: .
    ports:
      - "1100:80"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge 